# Generated by Django 2.0.2 on 2019-01-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=256, null=True)),
                ('poster', models.CharField(max_length=256, null=True)),
                ('singer', models.CharField(max_length=100, null=True)),
                ('Album', models.CharField(max_length=10, null=True)),
                ('medium', models.CharField(max_length=10, null=True)),
                ('genre', models.CharField(max_length=10, null=True)),
                ('releasetime', models.CharField(max_length=15, null=True)),
                ('publisher', models.CharField(max_length=15, null=True)),
                ('mark', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
